version: "3.8"

services:
  postgres:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ./config/migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: vault
      POSTGRES_DB: vault

  vault:
    image: vault:1.6.1
    command: vault server -config /vault/config
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    volumes:
      - ./config/vault.hcl:/vault/config/default.hcl

  vault-init:
    build: .
    image: vault-init:v0.0.0
    command: start
    depends_on:
      - postgres
      - vault
    environment:
      VAULT_ADDR: http://vault:8200
      ENCRYPTION_LOCAL_SECRET_KEY: FjaUCqqTIorGTe1Z86rs2YfkRgQ6iIgo
      STORAGE_POSTGRES_CONNECTION_URL: postgres://vault:vault@postgres:5432/vault?sslmode=disable
