name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-vault-init-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-vault-init-

      - name: Install dependencies
        run: |
          go mod tidy
          git diff --exit-code --name-only

      - name: Run linter
        run: |
          make fmt
          git diff --exit-code --name-only

      - name: Run tests
        run: make test

      - name: Compile binary
        run: make build
